# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Hilmm_multithreads <- function(y, b0, bedfile_in, outfile_in, thread, nmar, threadnumb) {
    invisible(.Call('_HiLMM_Hilmm_multithreads', PACKAGE = 'HiLMM', y, b0, bedfile_in, outfile_in, thread, nmar, threadnumb))
}

gblup_ebv <- function(y, h2) {
    .Call('_HiLMM_gblup_ebv', PACKAGE = 'HiLMM', y, h2)
}

Loglike <- function(sg, ynew, gnew, h2) {
    .Call('_HiLMM_Loglike', PACKAGE = 'HiLMM', sg, ynew, gnew, h2)
}

tugxy <- function(y, tugx) {
    .Call('_HiLMM_tugxy', PACKAGE = 'HiLMM', y, tugx)
}

tugxy2 <- function(y) {
    .Call('_HiLMM_tugxy2', PACKAGE = 'HiLMM', y)
}

Cposi_Choice <- function(b, ws) {
    .Call('_HiLMM_Cposi_Choice', PACKAGE = 'HiLMM', b, ws)
}

fast_jiont <- function(y, b0, position, thrd, bedfile_in) {
    .Call('_HiLMM_fast_jiont', PACKAGE = 'HiLMM', y, b0, position, thrd, bedfile_in)
}

